### ISSUE TITLE
MinGW release build broken on Windows.

### ISSUE THREAD

**Issue by dd01da0465b4542f8f8af4ecedc149ed** [PSI-Rockin/Corgi3DS#2]
It appears that MinGW (from Qt) release builds are broken but debug isn't.

Screenshot of issue:
![image](https://user-images.githubusercontent.com/24927193/57499211-d1b8c780-72ac-11e9-8422-053c55216cdd.png)

Possible libgmp issue? It also appears to have constant crashing.

**Comment by profi200** [comment]
Similar problem under Linux. Even though it decrypts the NAND image fine and the correct (sighax) signature comes out (verified through the logs) it fails with error code 0xDE. From 3dbrew: "FIRM header validation function failed: FIRM magicnum is invalid or RSA verification failed." Should be the later since magic validation already passed at that point.

**Comment by PSI-Rockin** [comment]
#11 fixes this, so closing.
